"""empty message

Revision ID: 5c44727f799d
Revises: a3607ef517e6
Create Date: 2023-08-29 22:17:24.193622

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5c44727f799d'
down_revision = 'a3607ef517e6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('films', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Title', sa.String(length=120), nullable=False))
        batch_op.add_column(sa.Column('Director', sa.String(length=80), nullable=False))
        batch_op.add_column(sa.Column('Produccion', sa.String(length=80), nullable=False))
        batch_op.add_column(sa.Column('Fecha_de_Estreno', sa.String(length=80), nullable=False))
        batch_op.drop_constraint('films_title_key', type_='unique')
        batch_op.create_unique_constraint(None, ['Title'])
        batch_op.drop_column('director')
        batch_op.drop_column('productor')
        batch_op.drop_column('title')

    with op.batch_alter_table('planets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Diameter', sa.String(length=80), nullable=False))
        batch_op.add_column(sa.Column('Rotation_Period', sa.String(length=80), nullable=False))
        batch_op.add_column(sa.Column('Orbital_Period', sa.String(length=80), nullable=False))
        batch_op.add_column(sa.Column('Gravity', sa.String(length=80), nullable=False))
        batch_op.add_column(sa.Column('Population', sa.String(length=80), nullable=False))
        batch_op.add_column(sa.Column('Climate', sa.String(length=80), nullable=False))
        batch_op.add_column(sa.Column('Terrain', sa.String(length=80), nullable=False))
        batch_op.add_column(sa.Column('Surface_Water', sa.String(length=80), nullable=False))
        batch_op.drop_column('population')
        batch_op.drop_column('terrain')

    with op.batch_alter_table('vehicle', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Modelo', sa.String(length=120), nullable=False))
        batch_op.add_column(sa.Column('Manufacturer', sa.String(length=80), nullable=False))
        batch_op.add_column(sa.Column('Cost_in_credits', sa.String(length=80), nullable=False))
        batch_op.add_column(sa.Column('Lenght', sa.String(length=80), nullable=False))
        batch_op.add_column(sa.Column('Max_Speed', sa.String(length=80), nullable=False))
        batch_op.add_column(sa.Column('Crew', sa.String(length=80), nullable=False))
        batch_op.add_column(sa.Column('Passengers', sa.String(length=80), nullable=False))
        batch_op.drop_constraint('vehicle_modelo_key', type_='unique')
        batch_op.create_unique_constraint(None, ['Modelo'])
        batch_op.drop_column('cost')
        batch_op.drop_column('lenght')
        batch_op.drop_column('modelo')
        batch_op.drop_column('manufacturer')
        batch_op.drop_column('crew')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vehicle', schema=None) as batch_op:
        batch_op.add_column(sa.Column('crew', sa.VARCHAR(length=80), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('manufacturer', sa.VARCHAR(length=80), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('modelo', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('lenght', sa.VARCHAR(length=80), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('cost', sa.VARCHAR(length=80), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_unique_constraint('vehicle_modelo_key', ['modelo'])
        batch_op.drop_column('Passengers')
        batch_op.drop_column('Crew')
        batch_op.drop_column('Max_Speed')
        batch_op.drop_column('Lenght')
        batch_op.drop_column('Cost_in_credits')
        batch_op.drop_column('Manufacturer')
        batch_op.drop_column('Modelo')

    with op.batch_alter_table('planets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('terrain', sa.VARCHAR(length=80), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('population', sa.VARCHAR(length=80), autoincrement=False, nullable=False))
        batch_op.drop_column('Surface_Water')
        batch_op.drop_column('Terrain')
        batch_op.drop_column('Climate')
        batch_op.drop_column('Population')
        batch_op.drop_column('Gravity')
        batch_op.drop_column('Orbital_Period')
        batch_op.drop_column('Rotation_Period')
        batch_op.drop_column('Diameter')

    with op.batch_alter_table('films', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('productor', sa.VARCHAR(length=80), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('director', sa.VARCHAR(length=80), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_unique_constraint('films_title_key', ['title'])
        batch_op.drop_column('Fecha_de_Estreno')
        batch_op.drop_column('Produccion')
        batch_op.drop_column('Director')
        batch_op.drop_column('Title')

    # ### end Alembic commands ###
