"""empty message

Revision ID: a3607ef517e6
Revises: da238272558e
Create Date: 2023-08-29 21:28:23.334529

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a3607ef517e6'
down_revision = 'da238272558e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('favorite',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('characters', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Name', sa.String(length=120), nullable=False))
        batch_op.add_column(sa.Column('Height', sa.String(length=80), nullable=False))
        batch_op.add_column(sa.Column('Mass', sa.String(length=80), nullable=False))
        batch_op.add_column(sa.Column('Hair_Color', sa.String(length=80), nullable=False))
        batch_op.add_column(sa.Column('Skin_Color', sa.String(length=80), nullable=False))
        batch_op.add_column(sa.Column('Eye_Color', sa.String(length=80), nullable=False))
        batch_op.add_column(sa.Column('Birth_Year', sa.String(length=80), nullable=False))
        batch_op.add_column(sa.Column('Gender', sa.String(length=80), nullable=False))
        batch_op.drop_constraint('characters_name_key', type_='unique')
        batch_op.create_unique_constraint(None, ['Name'])
        batch_op.drop_column('name')
        batch_op.drop_column('gender')
        batch_op.drop_column('eye_color')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('characters', schema=None) as batch_op:
        batch_op.add_column(sa.Column('eye_color', sa.VARCHAR(length=80), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('gender', sa.VARCHAR(length=80), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('name', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_unique_constraint('characters_name_key', ['name'])
        batch_op.drop_column('Gender')
        batch_op.drop_column('Birth_Year')
        batch_op.drop_column('Eye_Color')
        batch_op.drop_column('Skin_Color')
        batch_op.drop_column('Hair_Color')
        batch_op.drop_column('Mass')
        batch_op.drop_column('Height')
        batch_op.drop_column('Name')

    op.drop_table('favorite')
    # ### end Alembic commands ###
